name: Push to Main with mentioned tags Workflow

on:
  push:
    branches: [main]
    tags: v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "Building the project..."

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test Step
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 🚀 Deploy Step
        run: echo "Deploying the project..."
